/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EXT02D47194
 */
public class Example2 extends javax.swing.JFrame {

    /**
     * Creates new form Example2
     */
    public Example2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResult = new javax.swing.JLabel();
        txtNumber1 = new javax.swing.JTextField();
        txtNumber2 = new javax.swing.JTextField();
        btnAvarage = new javax.swing.JButton();
        btnSumming = new javax.swing.JButton();
        btnExtraction = new javax.swing.JButton();
        btnMultiplication = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnOtherExample = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblResult.setBackground(new java.awt.Color(0, 204, 102));
        lblResult.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult.setBorder(new javax.swing.border.MatteBorder(null));
        lblResult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblResult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtNumber1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtNumber2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnAvarage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAvarage.setText("AVARAGE");
        btnAvarage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvarageActionPerformed(evt);
            }
        });

        btnSumming.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSumming.setText("+");
        btnSumming.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSumming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSummingActionPerformed(evt);
            }
        });

        btnExtraction.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExtraction.setText("-");
        btnExtraction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtractionActionPerformed(evt);
            }
        });

        btnMultiplication.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMultiplication.setText("*");
        btnMultiplication.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicationActionPerformed(evt);
            }
        });

        btnDivision.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDivision.setText("/");
        btnDivision.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnOtherExample.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnOtherExample.setText("Other Example Page -->");
        btnOtherExample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtherExampleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOtherExample))
                    .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(txtNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnSumming)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAvarage)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExtraction)
                        .addGap(18, 18, 18)
                        .addComponent(btnMultiplication)
                        .addGap(18, 18, 18)
                        .addComponent(btnDivision)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAvarage)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumming)
                    .addComponent(btnExtraction)
                    .addComponent(btnMultiplication)
                    .addComponent(btnDivision))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnOtherExample)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvarageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvarageActionPerformed
        Base base = new Base();
        base.setNumber1(Integer.valueOf(txtNumber1.getText()));
        base.setNumber2(Integer.valueOf(txtNumber2.getText()));
        
        base.getResultAvarage();
        
        lblResult.setText(String.valueOf(base.getResultAvarage()));
    }//GEN-LAST:event_btnAvarageActionPerformed

    private void btnSummingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSummingActionPerformed
        Base base = new Base();
        base.setNumber1(Integer.valueOf(txtNumber1.getText()));
        base.setNumber2(Integer.valueOf(txtNumber2.getText()));
        
        base.getResultSumming();
        lblResult.setText(String.valueOf(base.getResultSumming()));
    }//GEN-LAST:event_btnSummingActionPerformed

    private void btnExtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtractionActionPerformed
        Base base = new Base();
        base.setNumber1(Integer.valueOf(txtNumber1.getText()));
        base.setNumber2(Integer.valueOf(txtNumber2.getText()));
        
        base.getResultExtraction();
        lblResult.setText(String.valueOf(base.getResultExtraction()));
    }//GEN-LAST:event_btnExtractionActionPerformed

    private void btnMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicationActionPerformed
        Base base = new Base();
        base.setNumber1(Integer.valueOf(txtNumber1.getText()));
        base.setNumber2(Integer.valueOf(txtNumber2.getText()));
        
        base.getResultMultiplication();
        lblResult.setText(String.valueOf(base.getResultMultiplication()));
    }//GEN-LAST:event_btnMultiplicationActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        Base base = new Base();
        base.setNumber1(Integer.valueOf(txtNumber1.getText()));
        base.setNumber2(Integer.valueOf(txtNumber2.getText()));
        
        base.getResultDivision();
        lblResult.setText(String.valueOf(base.getResultDivision()));
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnOtherExampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtherExampleActionPerformed
            OtherExample otherExample = new OtherExample();
            otherExample.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnOtherExampleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Example2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Example2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Example2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Example2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Example2().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvarage;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnExtraction;
    private javax.swing.JButton btnMultiplication;
    private javax.swing.JButton btnOtherExample;
    private javax.swing.JButton btnSumming;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField txtNumber1;
    private javax.swing.JTextField txtNumber2;
    // End of variables declaration//GEN-END:variables
}
